<?php

declare(strict_types=1);

return [
    [
        'id' => 'presentacion',
        'title' => 'Saludo y presentación',
        'contexts' => ['general'],
        'keywords' => ['hola', 'hey', 'buenas', 'saludos', 'que puedes', 'que eres', 'quien eres', 'que haces'],
        'answer' => '¡Hola, {name}! Soy tu asistente de "Ready for the Test?". Te ayudo con la calculadora, el laboratorio (catálogo, mezclas e identificación) y las salas de examen tipo Kahoot. Llevas {points} puntos. ¿Qué necesitas?',
        'suggestions' => ['¿Cómo gano puntos?', 'Mezclar reactivos', 'Unirme a una sala'],
    ],
    [
        'id' => 'agradecimiento',
        'title' => 'Agradecimiento',
        'contexts' => ['general'],
        'keywords' => ['gracias', 'genial', 'perfecto', 'excelente', 'ok', 'bueno', 'me gusto'],
        'answer' => '¡A la orden, {name}! Sigo aquí si necesitas otra cosa. Ánimo con la preparación para el examen.',
        'suggestions' => ['¿Cómo gano puntos?', 'Ver mi historial', 'Unirme a una sala'],
    ],
    [
        'id' => 'despedida',
        'title' => 'Despedida',
        'contexts' => ['general'],
        'keywords' => ['adios', 'chao', 'hasta luego', 'me voy', 'nos vemos', 'terminar', 'salir', 'despedida'],
        'answer' => '¡Hasta luego, {name}! La calculadora, el laboratorio y las salas de examen te esperan para que llegues listo al examen.',
        'suggestions' => ['¿Cómo gano puntos?', 'Unirme a una sala'],
    ],
    [
        'id' => 'como-empezar',
        'title' => 'Primeros pasos',
        'contexts' => ['general', 'laboratorio'],
        'keywords' => ['primeros pasos', 'por donde', 'que empiezo', 'comenzar', 'iniciar', 'principiante', 'no se', 'que hago'],
        'answer' => 'Empieza registrando una muestra con masa y volumen, experimenta mezclando reactivos en la mesa y practica en la calculadora. Cuando te sientas listo, únete a una sala de examen de tu docente.',
        'suggestions' => ['Registrar una muestra', 'Ver catálogo de sustancias', 'Mezclar reactivos'],
    ],
    [
        'id' => 'puntos-explicacion',
        'title' => 'Cómo ganar puntos',
        'contexts' => ['general', 'perfil'],
        'keywords' => ['ganar puntos', 'puntos', 'puntaje', 'subir', 'progreso', 'avance', 'ranking', 'score'],
        'answer' => 'Cada actividad del laboratorio otorga {base} puntos, descubrir una reacción nueva da {bonus} extra, y el puntaje de una sala de examen se suma directo a tu marcador. Llevas {points} puntos: {experiments} experimentos, {samples} muestras, {reactions} reacciones descubiertas y {quizzes} salas completadas.',
        'suggestions' => ['Ver mi perfil', 'Hacer una mezcla', 'Unirme a una sala'],
    ],
    [
        'id' => 'calculadora-basica',
        'title' => 'Calculadora básica',
        'contexts' => ['calculadora'],
        'keywords' => ['sumar', 'restar', 'multiplicar', 'dividir', 'basica', 'operacion', 'calcular', 'resultado', 'numeros'],
        'answer' => 'En la calculadora básica combina números con +, -, * y /. Escribe la operación, presiona el botón igual y el resultado se guarda automáticamente en tu historial.',
        'suggestions' => ['Explicar el historial', 'Usar funciones científicas'],
    ],
    [
        'id' => 'calculadora-cientifica',
        'title' => 'Calculadora científica',
        'contexts' => ['calculadora'],
        'keywords' => ['cientifica', 'raiz', 'cuadrada', 'potencia', 'elevado', 'seno', 'coseno', 'tangente', 'pi', 'log', 'funcion', 'trigonometrica'],
        'answer' => 'El modo científico incluye raíces, potencias, logaritmos y funciones trigonométricas (seno, coseno, tangente). Cambia a modo científico y sigue la sintaxis que muestra la ayuda en pantalla.',
        'suggestions' => ['Ver historial', 'Preguntar por operaciones básicas'],
    ],
    [
        'id' => 'calculadora-historial',
        'title' => 'Historial de operaciones',
        'contexts' => ['calculadora'],
        'keywords' => ['historial', 'guardar', 'registro', 'ultimas', 'anteriores', 'repetir', 'listado'],
        'answer' => 'Tus {calculations} operaciones se guardan y las últimas 50 aparecen en el historial, de la más reciente a la más antigua. Úsalo para repasar antes de la evaluación.',
        'suggestions' => ['Calcular algo nuevo', '¿Cómo gano puntos?'],
    ],
    [
        'id' => 'catalogo-sustancias',
        'title' => 'Catálogo de sustancias',
        'contexts' => ['catalogo'],
        'keywords' => ['sustancia', 'conocidas', 'propiedades', 'transparencia', 'conductividad', 'catalogo', 'estado', 'solido', 'liquido', 'gas'],
        'answer' => 'El catálogo lista sustancias conocidas con su densidad, transparencia, conductividad y estado. En la estación de identificación comparas esos valores para reconocer una muestra desconocida.',
        'suggestions' => ['¿Cómo identifico una muestra?', 'Mezclar reactivos'],
    ],
    [
        'id' => 'catalogo-reactivos',
        'title' => 'Reactivos y reacciones',
        'contexts' => ['catalogo'],
        'keywords' => ['reactivo', 'recetario', 'efectos', 'burbujea', 'colorea', 'precipita', 'espuma', 'color'],
        'answer' => 'La mesa de mezclas usa reactivos con colores y efectos (burbujea, espuma, precipita, colorea). El recetario muestra las reacciones que ya descubriste: tu reto es probar todas las combinaciones.',
        'suggestions' => ['Descubrir reacciones', '¿Cómo gano puntos?'],
    ],
    [
        'id' => 'mezclas-como',
        'title' => 'Mesa de mezclas',
        'contexts' => ['mezclas'],
        'keywords' => ['mezclar', 'combinar', 'seleccionar', 'reaccion', 'mesa', 'probar', 'donde'],
        'answer' => 'Elige dos reactivos en la mesa de mezclas. Si la combinación tiene reacción, se guarda en tu recetario; cada mezcla registra una actividad de {base} puntos.',
        'suggestions' => ['Descubrir reacciones nuevas', 'Ver el recetario', 'Ganar puntos extra'],
    ],
    [
        'id' => 'mezclas-descubrir',
        'title' => 'Descubrir reacciones',
        'contexts' => ['mezclas'],
        'keywords' => ['descubrir', 'descubrimiento', 'nueva', 'inventar', 'sorpresa', 'bonus', 'primera vez', 'desconocida', 'combinacion'],
        'answer' => 'Al descubrir una reacción por primera vez ganas {bonus} puntos además de los {base} de la actividad. Tienes {reactions} descubiertas: prueba combinaciones nuevas para sumar más.',
        'suggestions' => ['¿Cómo gano puntos?', 'Ir a la mesa de mezclas'],
    ],
    [
        'id' => 'identificacion-como',
        'title' => 'Estación de identificación',
        'contexts' => ['identificacion'],
        'keywords' => ['identificar', 'identificacion', 'estacion', 'desconocida', 'medir', 'comparar', 'densidad', 'descubrir muestra'],
        'answer' => 'Ingresa masa y volumen de la muestra desconocida para calcular su densidad y compárala con el catálogo usando transparencia, conductividad y estado. Al acertar, la identificación queda registrada.',
        'suggestions' => ['Ver catálogo de sustancias', 'Ver mi historial', '¿Cómo gano puntos?'],
    ],
    [
        'id' => 'muestras',
        'title' => 'Muestras del laboratorio',
        'contexts' => ['laboratorio'],
        'keywords' => ['muestra', 'registrar', 'crear muestra', 'nueva muestra', 'masa', 'volumen', 'eliminar', 'borrar'],
        'answer' => 'Registra muestras con nombre, masa y volumen y bórralas cuando ya no las uses. Llevas {samples} muestras; su densidad se usa en las estaciones del laboratorio.',
        'suggestions' => ['Identificar una muestra', 'Ver mi historial', 'Mezclar reactivos'],
    ],
    [
        'id' => 'historial-experimentos',
        'title' => 'Historial de experimentos',
        'contexts' => ['laboratorio'],
        'keywords' => ['historial', 'experimento', 'actividad', 'registro', 'resultados', 'resumen', 'todas'],
        'answer' => 'Llevas {experiments} experimentos registrados (densidad, temperatura, identificación, masa/volumen y mezclas) con sus puntos. Repásalos antes de la sala de examen.',
        'suggestions' => ['¿Cómo gano puntos?', 'Ir a una sala de examen', 'Registrar una muestra'],
    ],
    [
        'id' => 'salas-crear',
        'title' => 'Crear una sala de examen',
        'contexts' => ['salas'],
        'keywords' => ['crear sala', 'crear examen', 'docente', 'nueva sala', 'organizar', 'activa', 'codigo'],
        'answer' => 'Como docente creas una sala con título y entre 1 y 20 preguntas de 4 opciones, indicando la opción correcta y sus puntos (1 a 100). El sistema genera un código único para que los estudiantes se unan.',
        'suggestions' => ['Ver mis salas', '¿Cómo se unen los estudiantes?', '¿Cómo se califica?'],
    ],
    [
        'id' => 'salas-unirse',
        'title' => 'Unirse a una sala',
        'contexts' => ['salas'],
        'keywords' => ['unir', 'join', 'codigo', 'entrar', 'participar', 'estudiante', 'unirme', 'partida'],
        'answer' => 'Como estudiante ingresa el código de 6 caracteres que compartió tu docente. Verás las preguntas sin la respuesta correcta; respondes una sola vez y el puntaje se suma a tus puntos totales.',
        'suggestions' => ['¿Cómo se califica?', 'Ver mi puntaje', 'Crear una sala'],
    ],
    [
        'id' => 'salas-calificacion',
        'title' => 'Calificación de la sala',
        'contexts' => ['salas'],
        'keywords' => ['calificar', 'puntaje', 'resultado', 'nota', 'aciertos', 'correctas', 'intento', 'feedback', 'cuanto vale'],
        'answer' => 'Cada pregunta vale los puntos que definió el docente. Hay un solo intento por estudiante y por sala: tus aciertos suman al marcador final y se agregan a tus puntos del perfil.',
        'suggestions' => ['Unirme a una sala', 'Ver mi avance', '¿Cómo gano puntos?'],
    ],
    [
        'id' => 'examen-kata',
        'title' => 'Preparación para la evaluación',
        'contexts' => ['salas', 'general'],
        'keywords' => ['examen', 'kata', 'evaluacion', 'test', 'listo', 'preparar', 'practicar', 'repasar', 'estudiar'],
        'answer' => 'Para el examen repasa tu historial de operaciones y experimentos, usa el catálogo y el recetario, y mídete entrando a una sala de examen de tu docente. Llevas {points} puntos de avance.',
        'suggestions' => ['Ver mi historial', 'Identificar una muestra', 'Crear una sala de examen'],
    ],
];